// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClgR3KHmg54MimafY97wKLKYm0ed8qkx4',
    appId: '1:467163872531:web:844d39cef78770ba3f6ee6',
    messagingSenderId: '467163872531',
    projectId: 'hambola-f3945',
    authDomain: 'hambola-f3945.firebaseapp.com',
    storageBucket: 'hambola-f3945.appspot.com',
    measurementId: 'G-1SGD778795',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFh5vQWp96c3nN_IkHDZPFhYKQIKXm9so',
    appId: '1:467163872531:android:b4d093ed9ffb9d933f6ee6',
    messagingSenderId: '467163872531',
    projectId: 'hambola-f3945',
    storageBucket: 'hambola-f3945.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUswLDIf5Y2C_BMZnGQLuu15mCbEbvP08',
    appId: '1:467163872531:ios:2379c0c0583f26df3f6ee6',
    messagingSenderId: '467163872531',
    projectId: 'hambola-f3945',
    storageBucket: 'hambola-f3945.appspot.com',
    iosBundleId: 'com.example.hambolahChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUswLDIf5Y2C_BMZnGQLuu15mCbEbvP08',
    appId: '1:467163872531:ios:a79533a4dde04f793f6ee6',
    messagingSenderId: '467163872531',
    projectId: 'hambola-f3945',
    storageBucket: 'hambola-f3945.appspot.com',
    iosBundleId: 'com.example.hambolahChatApp.RunnerTests',
  );
}
